test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon:
  service: S3
  access_key_id:     <%= CGI.unescape(URI.parse(ENV['S3_DATA_URL']).user) %>
  secret_access_key: <%= CGI.unescape(URI.parse(ENV['S3_DATA_URL']).password) %>
  region:            <%= CGI.parse(URI.parse(ENV['S3_DATA_URL']).query)['region'].first %>
  bucket:            <%= URI.parse(ENV['S3_DATA_URL']).path[1..-1] %>
  endpoint:          https://<%= URI.parse(ENV['S3_DATA_URL']).host %>
